"""empty message

Revision ID: bef33eeb8824
Revises: f392f8e1ff88
Create Date: 2018-09-25 08:47:45.305036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef33eeb8824'
down_revision = 'f392f8e1ff88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
