"""empty message

Revision ID: cc74994fc101
Revises: dc724439a73a
Create Date: 2018-09-28 21:25:56.015516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc74994fc101'
down_revision = 'dc724439a73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'create_time')
    # ### end Alembic commands ###
