"""empty message

Revision ID: f392f8e1ff88
Revises: b3a8ed604978
Create Date: 2018-09-25 08:47:31.779262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f392f8e1ff88'
down_revision = 'b3a8ed604978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
